version: '2.2'

services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - archteamsweb
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
  archteamsweb:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn arch_teams_qna.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/home/app/web
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  static_volume:
  postgres_data:
  media_volume:
