# Generated by Django 3.0.5 on 2020-04-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='avatar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
