# Generated by Django 3.0.5 on 2020-04-06 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapi', '0002_auto_20200404_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=65000)),
                ('up_votes', models.IntegerField(blank=True, default=0)),
                ('down_votes', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnaapi.ArchTeamsQnaUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('sub_title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(max_length=65000)),
                ('up_votes', models.IntegerField(blank=True, default=0)),
                ('down_votes', models.IntegerField(blank=True, default=0)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qnaapi.ArchTeamsQnaUser')),
                ('tags', models.ManyToManyField(to='qnaapi.Tag')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnaapi.Team')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=65000)),
                ('up_votes', models.IntegerField(blank=True, default=0)),
                ('down_votes', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnaapi.ArchTeamsQnaUser')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnaapi.Question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=65000)),
                ('up_votes', models.IntegerField(blank=True, default=0)),
                ('down_votes', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnaapi.Answer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnaapi.ArchTeamsQnaUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnaapi.Question'),
        ),
    ]
