# Generated by Django 3.0.5 on 2020-04-06 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapi', '0004_auto_20200406_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='description',
            new_name='content',
        ),
    ]
