# Generated by Django 3.0.5 on 2020-04-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapi', '0007_auto_20200419_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='up_votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='views',
        ),
        migrations.CreateModel(
            name='QuestionVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', 'Up Voted'), ('down', 'Down Voted')], default='up', max_length=4)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnaapi.Question')),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qnaapi.ArchTeamsQnaUser')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnaapi.Question')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qnaapi.ArchTeamsQnaUser')),
            ],
        ),
    ]
