# Generated by Django 3.0.5 on 2020-04-25 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapi', '0008_auto_20200425_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', 'Up Voted'), ('down', 'Down Voted')], default='up', max_length=4)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qnaapi.Answer')),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qnaapi.ArchTeamsQnaUser')),
            ],
        ),
    ]
