# Generated by Django 3.0.5 on 2020-04-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapi', '0011_auto_20200426_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archteamsqnauser',
            name='rating',
        ),
    ]
