# Generated by Django 3.0.5 on 2020-04-30 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapi', '0012_remove_archteamsqnauser_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('add_question', 'Add Question'), ('add_question_comment', 'Add Question Comment'), ('add_answer', 'Add Question Answer'), ('edit_question', 'Edit Question'), ('up_vote_question', 'Up Vote Question'), ('down_vote_question', 'Down Vote Question'), ('add_answer_comment', 'Add Answer Comment'), ('edit_answer', 'Edit Answer Comment'), ('up_vote_answer', 'Up Vote Answer'), ('down_vote_answer', 'Down Vote Answer'), ('accept_answer', 'Accept Answer'), ('edit_question_comment', 'Edit Question Comment'), ('edit_answer_comment', 'Edit Answer Comment')], max_length=200)),
                ('message', models.TextField(blank=True, max_length=65000, null=True)),
                ('action_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_activities', to='qnaapi.ArchTeamsQnaUser')),
                ('affected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affected_activities', to='qnaapi.ArchTeamsQnaUser')),
            ],
        ),
    ]
