# Generated by Django 3.0.5 on 2020-04-30 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapi', '0013_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='affected_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qnaapi.Team'),
        ),
    ]
