# Generated by Django 3.0.5 on 2020-04-30 17:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapi', '0014_activitylog_affected_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
