# Generated by Django 3.0.5 on 2020-05-07 11:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import qnaapi.models.qna


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapi', '0015_activitylog_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archteamsqnauser',
            name='avatar',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=qnaapi.models.qna.default_user_avatar, null=True),
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
