# Generated by Django 3.0.6 on 2020-05-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapi', '0016_auto_20200507_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='qnaapi.Tag'),
        ),
    ]
